# Generated by Django 4.2.4 on 2023-09-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.presupuesto')),
            ],
        ),
    ]
