# Generated by Django 4.2.4 on 2023-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
