# Generated by Django 4.2.4 on 2023-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_presupuesto_vencido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
